apiVersion: v1
kind: Service
metadata:
  name: python-dev-environment
spec:
  selector:
    app: python-dev-environment
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}