global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#project'
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
